language: node_js

node_js:
- 'lts/*'
install:
  - npm install

jobs:
  include:
    - stage: Eslint # uses the default stage name "test"
    - script: npm run lint
    - stage: Test
    - script: npm run test
